# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: world.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bworld.proto\"(\n\x06\x45ntity\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08position\x18\x03 \x03(\r\"j\n\x05World\x12\'\n\x08\x65ntities\x18\x80\x02 \x03(\x0b\x32\x14.World.EntitiesEntry\x1a\x38\n\rEntitiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x16\n\x05value\x18\x02 \x01(\x0b\x32\x07.Entity:\x02\x38\x01\x62\x06proto3')



_ENTITY = DESCRIPTOR.message_types_by_name['Entity']
_WORLD = DESCRIPTOR.message_types_by_name['World']
_WORLD_ENTITIESENTRY = _WORLD.nested_types_by_name['EntitiesEntry']
Entity = _reflection.GeneratedProtocolMessageType('Entity', (_message.Message,), {
  'DESCRIPTOR' : _ENTITY,
  '__module__' : 'world_pb2'
  # @@protoc_insertion_point(class_scope:Entity)
  })
_sym_db.RegisterMessage(Entity)

World = _reflection.GeneratedProtocolMessageType('World', (_message.Message,), {

  'EntitiesEntry' : _reflection.GeneratedProtocolMessageType('EntitiesEntry', (_message.Message,), {
    'DESCRIPTOR' : _WORLD_ENTITIESENTRY,
    '__module__' : 'world_pb2'
    # @@protoc_insertion_point(class_scope:World.EntitiesEntry)
    })
  ,
  'DESCRIPTOR' : _WORLD,
  '__module__' : 'world_pb2'
  # @@protoc_insertion_point(class_scope:World)
  })
_sym_db.RegisterMessage(World)
_sym_db.RegisterMessage(World.EntitiesEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WORLD_ENTITIESENTRY._options = None
  _WORLD_ENTITIESENTRY._serialized_options = b'8\001'
  _ENTITY._serialized_start=15
  _ENTITY._serialized_end=55
  _WORLD._serialized_start=57
  _WORLD._serialized_end=163
  _WORLD_ENTITIESENTRY._serialized_start=107
  _WORLD_ENTITIESENTRY._serialized_end=163
# @@protoc_insertion_point(module_scope)
